name: "Daily Checks"

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        configuration: 
          - { config: 'fenix', 'android-components', 'reference-browser'}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run script
        id: runClient
        run: |
          echo '${{ matrix.configuration['config'] }}'
